
2024-02-21 18:34:56,158 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 18:34:56,158 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 18:34:56,158 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 18:34:56,158 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 18:34:56,158 - ERROR - Error: [Errno 13] Permission denied: './services_sh/start_posgresql.sh'
2024-02-21 18:34:56,158 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 18:34:56,158 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 18:34:56,158 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:34:56,158 - INFO - [96mPassword:        Oo51knSSV3OSwfuy8WFu[0m
2024-02-21 18:35:01,757 - ERROR - Error occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 2.
2024-02-21 18:35:01,757 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 18:35:01,757 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:36:14,010 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 18:36:14,010 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 18:36:14,010 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 18:36:14,010 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 18:36:14,010 - ERROR - Error: [Errno 13] Permission denied: './services_sh/start_posgresql.sh'
2024-02-21 18:36:14,010 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 18:36:14,010 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 18:36:14,010 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:36:14,010 - INFO - [96mPassword:        Oo51knSSV3OSwfuy8WFu[0m
2024-02-21 18:36:19,169 - ERROR - Error occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 130.
2024-02-21 18:36:19,169 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 18:36:19,169 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:38:44,487 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 18:38:44,487 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 18:38:44,488 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 18:38:44,488 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 18:38:50,776 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 18:38:50,776 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 18:38:50,776 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 18:38:50,776 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:38:50,776 - INFO - [96mPassword:        Oo51knSSV3OSwfuy8WFu[0m
2024-02-21 18:39:20,216 - ERROR - Error occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 2.
2024-02-21 18:39:20,216 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 18:39:20,216 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:39:34,015 - ERROR - Error occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.
2024-02-21 18:39:34,015 - INFO - [92mThe error should indicate 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 18:39:34,015 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 18:39:34,015 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 18:39:34,060 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 18:39:34,060 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 18:39:34,060 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 18:39:34,060 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 18:41:51,358 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 18:41:51,359 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 18:41:51,359 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 18:41:51,359 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 18:41:57,629 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 18:41:57,629 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 18:41:57,629 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 18:41:57,629 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:41:57,629 - INFO - [96mPassword:        Oo51knSSV3OSwfuy8WFu[0m
2024-02-21 18:42:02,734 - ERROR - Error occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 130.
2024-02-21 18:42:02,734 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 18:42:02,746 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:42:42,326 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 18:42:42,326 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 18:42:42,327 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 18:42:42,327 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 18:42:42,336 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 18:42:42,336 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 18:42:42,336 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 18:42:42,336 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:42:42,336 - INFO - [96mPassword:        Oo51knSSV3OSwfuy8WFu[0m
2024-02-21 18:42:52,088 - INFO - [92mUser project_google_reviews_usr created successfully.[0m
2024-02-21 18:42:52,088 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 18:42:52,088 - INFO - [96mUser:            project_google_reviews_usr[0m
2024-02-21 18:42:57,504 - ERROR - Error occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.
2024-02-21 18:42:57,505 - INFO - [92mThe error should indicate 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 18:42:57,508 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 18:42:57,508 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 18:42:57,552 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 18:42:57,552 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 18:42:57,552 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 18:42:57,552 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 19:14:08,812 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 19:14:08,812 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 19:14:08,812 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 19:14:08,812 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 19:14:55,727 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 19:14:55,727 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 19:14:55,727 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 19:14:55,727 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 19:15:08,880 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 19:15:08,880 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 19:15:08,880 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 19:15:08,880 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:15:08,880 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 19:15:15,659 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 19:15:15,660 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 19:15:15,660 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:15:22,776 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 19:15:22,776 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 19:15:22,776 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 19:15:22,776 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 19:15:22,831 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 19:15:22,831 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 19:15:22,831 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 19:15:22,831 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 19:17:07,029 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 19:17:07,029 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 19:17:07,029 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 19:17:07,029 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 19:17:13,300 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 19:17:13,300 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 19:17:13,300 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 19:17:13,300 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:17:13,300 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 19:17:16,420 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 19:17:16,420 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 19:17:16,420 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:17:27,460 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 19:17:27,460 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 19:17:27,460 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 19:17:27,468 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 19:17:27,468 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 19:17:27,468 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 19:17:27,468 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 19:17:27,468 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 19:17:27,468 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 19:17:27,468 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 19:17:27,468 - INFO - [96mAttempting to create database:[0m
2024-02-21 19:17:27,468 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:17:27,468 - ERROR - [91mAn error occurred: CREATE DATABASE cannot run inside a transaction block
[0m
2024-02-21 19:17:27,468 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 19:17:27,469 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:17:27,472 - ERROR - [91mAn error occurred: current transaction is aborted, commands ignored until end of transaction block
[0m
2024-02-21 19:17:27,472 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 19:17:27,473 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 19:17:27,512 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 19:17:27,512 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 19:17:27,512 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 19:17:27,534 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 19:23:37,268 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 19:23:37,268 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 19:23:37,268 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 19:23:37,268 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 19:23:43,528 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 19:23:43,528 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 19:23:43,529 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 19:23:43,529 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:23:43,529 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 19:23:46,836 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 19:23:46,837 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 19:23:46,837 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:23:50,573 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 19:23:50,573 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 19:23:50,573 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 19:23:50,580 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 19:23:50,580 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 19:23:50,580 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 19:23:50,580 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 19:23:50,581 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 19:23:50,581 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 19:23:50,581 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 19:23:50,581 - INFO - [96mAttempting to create database:[0m
2024-02-21 19:23:50,581 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:23:50,668 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 19:23:50,668 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:23:50,675 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 19:23:50,675 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 19:23:50,675 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 19:23:50,723 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 19:23:50,723 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 19:23:50,723 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 19:23:50,744 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 19:30:22,557 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 19:30:22,557 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 19:30:22,557 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 19:30:22,557 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 19:30:22,566 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 19:30:22,566 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 19:30:22,566 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 19:30:22,566 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:30:22,566 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 19:30:29,190 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 19:30:29,190 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 19:30:29,190 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:30:37,819 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 19:30:37,819 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 19:30:37,819 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 19:30:37,827 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 19:30:37,827 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 19:30:37,827 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 19:30:37,827 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 19:30:37,827 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 19:30:37,827 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 19:30:37,827 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 19:30:37,827 - INFO - [96mAttempting to create database:[0m
2024-02-21 19:30:37,827 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:30:37,867 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 19:30:37,867 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 19:30:37,867 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:30:37,868 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 19:30:37,868 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 19:30:37,868 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 19:30:37,895 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 19:30:37,895 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 19:30:37,895 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 19:30:37,915 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 19:31:43,756 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 19:31:43,756 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 19:31:43,756 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 19:31:43,756 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 19:31:50,029 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 19:31:50,029 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 19:31:50,029 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 19:31:50,029 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:31:50,029 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 19:31:55,124 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 19:31:55,125 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 19:31:55,125 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 19:32:01,237 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 19:32:01,237 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 19:32:01,237 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 19:32:01,245 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 19:32:01,245 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 19:32:01,245 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 19:32:01,245 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 19:32:01,245 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 19:32:01,245 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 19:32:01,245 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 19:32:01,245 - INFO - [96mAttempting to create database:[0m
2024-02-21 19:32:01,245 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:32:01,245 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 19:32:01,245 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 19:32:01,245 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 19:32:01,246 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 19:32:01,246 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 19:32:01,246 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 19:32:01,284 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 19:32:01,284 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 19:32:01,284 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 19:32:01,303 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 21:58:30,757 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 21:58:30,758 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 21:58:30,758 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 21:58:30,758 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 21:58:40,437 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 21:58:40,437 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 21:58:40,437 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 21:58:40,437 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 21:58:40,437 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 21:58:43,592 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 21:58:43,592 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 21:58:43,592 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 21:58:46,709 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 21:58:46,709 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 21:58:46,709 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 21:58:46,729 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 21:58:46,729 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 21:58:46,729 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 21:58:46,729 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 21:58:46,729 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 21:58:46,729 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 21:58:46,729 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 21:58:46,729 - INFO - [96mAttempting to create database:[0m
2024-02-21 21:58:46,729 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 21:58:46,730 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 21:58:46,730 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 21:58:46,730 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 21:58:46,737 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 21:58:46,737 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 21:58:46,737 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 21:58:46,785 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 21:58:46,785 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 21:58:46,785 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 21:58:46,801 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 21:58:46,801 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 21:58:46,802 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 21:58:46,802 - ERROR - Error: [Errno 2] No such file or directory: './services_sh/restart_postgresql.sh'
2024-02-21 21:58:46,802 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 21:58:46,815 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:00:18,344 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:00:18,344 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:00:18,344 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:00:18,344 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:00:24,609 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:00:24,609 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:00:24,609 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:00:24,609 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:00:24,609 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:00:27,139 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:00:27,139 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:00:27,139 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:00:29,553 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:00:29,553 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:00:29,553 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:00:29,561 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:00:29,561 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:00:29,561 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:00:29,561 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:00:29,561 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:00:29,561 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:00:29,561 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:00:29,561 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:00:29,561 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:00:29,562 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:00:29,562 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:00:29,562 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:00:29,562 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:00:29,562 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:00:29,562 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:00:29,609 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:00:29,609 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:00:29,613 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:00:29,628 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:00:29,628 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:00:29,628 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:00:29,628 - ERROR - Error: [Errno 2] No such file or directory: './services_sh/restart_postgresql.sh'
2024-02-21 22:00:29,628 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:00:29,642 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:00:43,864 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:00:43,864 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:00:43,864 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:00:43,864 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:00:50,125 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:00:50,125 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:00:50,125 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:00:50,126 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:00:50,126 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:00:52,482 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:00:52,483 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:00:52,483 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:00:54,301 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:00:54,301 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:00:54,301 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:00:54,309 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:00:54,309 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:00:54,309 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:00:54,309 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:00:54,309 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:00:54,309 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:00:54,309 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:00:54,309 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:00:54,309 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:00:54,310 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:00:54,310 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:00:54,310 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:00:54,310 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:00:54,310 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:00:54,311 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:00:54,341 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:00:54,341 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:00:54,341 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:00:54,356 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:00:54,356 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:00:54,356 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:00:54,356 - ERROR - Error: [Errno 2] No such file or directory: '/services_sh/restart_postgresql.sh'
2024-02-21 22:00:54,356 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:00:54,370 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:03:29,435 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:03:29,435 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:03:29,435 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:03:29,435 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:03:35,701 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:03:35,701 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:03:35,701 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:03:35,701 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:03:35,701 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:03:41,875 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 2.[0m
2024-02-21 22:03:41,875 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:03:41,875 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:03:48,561 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:03:48,561 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:03:48,561 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:03:48,570 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:03:48,571 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:03:48,571 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:03:48,571 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:03:48,571 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:03:48,571 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:03:48,571 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:03:48,571 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:03:48,571 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:03:48,571 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:03:48,571 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:03:48,571 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:03:48,572 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:03:48,572 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:03:48,572 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:03:48,625 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:03:48,625 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:03:48,625 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:03:48,640 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:03:48,640 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:03:48,640 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:03:55,001 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 22:03:55,001 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:03:55,013 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:18:16,754 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:18:16,754 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:18:16,754 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:18:16,754 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:18:16,763 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:18:16,763 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:18:16,763 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:18:16,763 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:18:16,763 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:18:19,404 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:18:19,404 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:18:19,404 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:18:23,128 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:18:23,128 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:18:23,128 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:18:23,137 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:18:23,137 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:18:23,137 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:18:23,137 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:18:23,137 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:18:23,137 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:18:23,137 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:18:23,137 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:18:23,137 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:18:23,137 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:18:23,137 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:18:23,137 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:18:23,138 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:18:23,138 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:18:23,138 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:18:23,188 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:18:23,189 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:18:23,189 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:18:23,201 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:18:23,201 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 22:18:23,202 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 22:18:23,202 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:18:23,202 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 22:18:23,202 - INFO - [94mAttempting to add following line:[0m
2024-02-21 22:18:23,202 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:18:23,202 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD
local	  all	  example_user	  md5[0m
2024-02-21 22:18:23,202 - INFO - [95mlocal	  project_google_reviews	      project_google_reviews_usr         md5[0m
2024-02-21 22:18:23,202 - ERROR - An error occurred while editing pg_hba.conf: [Errno 13] Permission denied: '/etc/postgresql/16/main/pg_hba.conf'
2024-02-21 22:18:23,202 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:18:23,202 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:18:29,605 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 22:18:29,605 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:18:29,605 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:18:29,618 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:27:02,029 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:27:02,029 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:27:02,029 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:27:02,029 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:27:02,039 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:27:02,039 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:27:02,039 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:27:02,039 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:27:02,039 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:27:04,543 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:27:04,543 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:27:04,543 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:27:12,309 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:27:12,309 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:27:12,309 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:27:12,316 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:27:12,317 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:27:12,317 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:27:12,317 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:27:12,317 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:27:12,317 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:27:12,317 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:27:12,317 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:27:12,317 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:27:12,317 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:27:12,317 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:27:12,317 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:27:12,318 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:27:12,318 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:27:12,318 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:27:12,349 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:27:12,349 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:27:12,349 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:27:12,362 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:27:12,362 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 22:27:12,362 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 22:27:12,362 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:27:12,362 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 22:27:12,362 - INFO - [94mAttempting to add following line:[0m
2024-02-21 22:27:12,362 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:27:12,362 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-21 22:27:12,362 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-21 22:27:12,362 - ERROR - An error occurred while editing pg_hba.conf: [Errno 13] Permission denied: '/etc/postgresql/16/main/pg_hba.conf'
2024-02-21 22:27:12,362 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:27:12,362 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:27:18,733 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 22:27:18,733 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:27:18,733 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:27:18,748 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:28:57,354 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:28:57,354 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:28:57,354 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:28:57,354 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:28:57,364 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:28:57,364 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:28:57,364 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:28:57,364 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:28:57,364 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:29:00,029 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:29:00,029 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:29:00,029 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:29:09,697 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:29:09,697 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:29:09,697 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:29:09,705 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:29:09,705 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:29:09,705 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:29:09,705 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:29:09,705 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:29:09,705 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:29:09,705 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:29:09,705 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:29:09,705 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:29:09,705 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:29:09,705 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:29:09,706 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:29:09,706 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:29:09,706 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:29:09,706 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:29:09,769 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:29:09,769 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:29:09,769 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:29:09,781 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:29:09,782 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 22:29:09,782 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 22:29:09,782 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:29:09,782 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 22:29:09,782 - INFO - [94mAttempting to add following line:[0m
2024-02-21 22:29:09,782 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:29:09,782 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-21 22:29:09,782 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-21 22:29:09,782 - ERROR - An error occurred while editing pg_hba.conf: [Errno 13] Permission denied: '/etc/postgresql/16/main/pg_hba.conf'
2024-02-21 22:29:09,782 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:29:09,782 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:29:16,165 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 22:29:16,165 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:29:16,165 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:29:16,177 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:32:33,916 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:32:33,916 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:32:33,916 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:32:33,916 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:32:33,925 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:32:33,925 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:32:33,926 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:32:33,926 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:32:33,926 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:32:36,239 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:32:36,239 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:32:36,239 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:32:45,800 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:32:45,800 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:32:45,800 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:32:45,809 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:32:45,809 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:32:45,809 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:32:45,809 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:32:45,809 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:32:45,809 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:32:45,809 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:32:45,809 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:32:45,809 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:32:45,809 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:32:45,809 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:32:45,809 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:32:45,810 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:32:45,810 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:32:45,811 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:32:45,848 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:32:45,848 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:32:45,848 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:32:45,861 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:32:45,861 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 22:32:45,861 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 22:32:45,861 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:32:45,861 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 22:32:45,861 - INFO - [94mAttempting to add following line:[0m
2024-02-21 22:32:45,861 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:32:45,861 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-21 22:32:45,861 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-21 22:32:45,862 - ERROR - An error occurred while editing pg_hba.conf: [Errno 13] Permission denied: '/etc/postgresql/16/main/pg_hba.conf'
2024-02-21 22:32:45,862 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:32:45,862 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:32:52,272 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 22:32:52,272 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:32:52,272 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:32:52,284 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:35:16,412 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:35:16,412 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:35:16,412 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:35:16,412 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:35:16,422 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:35:16,422 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:35:16,422 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:35:16,422 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:35:16,422 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:35:18,538 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:35:18,538 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:35:18,538 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:35:20,541 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:35:20,541 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:35:20,541 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:35:20,549 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:35:20,549 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:35:20,549 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:35:20,549 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:35:20,549 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:35:20,549 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:35:20,549 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:35:20,549 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:35:20,549 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:35:20,549 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:35:20,549 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:35:20,549 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:35:20,550 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:35:20,550 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:35:20,550 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:35:20,593 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:35:20,593 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:35:20,593 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:35:20,607 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:35:20,607 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 22:35:20,607 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 22:35:20,607 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:35:20,607 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 22:35:20,607 - INFO - [94mAttempting to add following line:[0m
2024-02-21 22:35:20,607 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:35:20,607 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-21 22:35:20,607 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-21 22:35:20,607 - ERROR - An error occurred while editing pg_hba.conf: [Errno 13] Permission denied: '/etc/postgresql/16/main/pg_hba.conf'
2024-02-21 22:35:20,607 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:35:20,607 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:35:26,973 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 22:35:26,973 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:35:26,973 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:35:26,985 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:39:14,839 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 22:39:14,839 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 22:39:14,839 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 22:39:14,839 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 22:39:14,849 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 22:39:14,849 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 22:39:14,849 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 22:39:14,849 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:39:14,849 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 22:39:17,482 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 22:39:17,483 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 22:39:17,483 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 22:39:19,637 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 22:39:19,637 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 22:39:19,637 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 22:39:19,645 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 22:39:19,645 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 22:39:19,645 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 22:39:19,645 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 22:39:19,645 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 22:39:19,645 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 22:39:19,645 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 22:39:19,645 - INFO - [96mAttempting to create database:[0m
2024-02-21 22:39:19,645 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:39:19,645 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 22:39:19,645 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 22:39:19,645 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 22:39:19,646 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 22:39:19,646 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:39:19,646 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 22:39:19,700 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 22:39:19,700 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:39:19,700 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:39:19,714 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 22:39:19,714 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 22:39:19,714 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 22:39:19,714 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:39:19,714 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 22:39:19,714 - INFO - [94mAttempting to add following line:[0m
2024-02-21 22:39:19,714 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 22:39:19,714 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-21 22:39:19,714 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-21 22:39:19,714 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-21 22:39:19,714 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 22:39:19,714 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 22:39:26,109 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 22:39:26,109 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 22:39:26,109 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 22:39:26,122 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 23:05:31,567 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 23:05:31,567 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 23:05:31,567 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 23:05:31,567 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 23:06:03,950 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 23:06:03,950 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 23:06:03,950 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 23:06:03,950 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 23:06:03,961 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 23:06:03,961 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 23:06:03,961 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 23:06:03,961 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 23:06:03,961 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 23:06:06,790 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 23:06:06,790 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 23:06:06,790 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 23:06:09,377 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 23:06:09,377 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 23:06:09,380 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 23:06:09,389 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 23:06:09,389 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 23:06:09,389 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 23:06:09,389 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 23:06:09,389 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 23:06:09,389 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 23:06:09,389 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 23:06:09,389 - INFO - [96mAttempting to create database:[0m
2024-02-21 23:06:09,389 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 23:06:09,390 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 23:06:09,390 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 23:06:09,390 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 23:06:09,390 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 23:06:09,391 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 23:06:09,391 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 23:06:09,424 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 23:06:09,424 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 23:06:09,424 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 23:06:09,437 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 23:06:09,437 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 23:06:09,438 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 23:06:09,438 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 23:06:09,438 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 23:06:09,438 - INFO - [94mAttempting to add following line:[0m
2024-02-21 23:06:09,438 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 23:06:09,438 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-21 23:06:09,438 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-21 23:06:09,438 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-21 23:06:09,438 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 23:06:09,438 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 23:06:15,832 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 23:06:15,833 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 23:06:15,833 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 23:06:15,845 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 23:06:15,845 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-21 23:06:15,846 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-21 23:06:15,846 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 23:06:24,433 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-21 23:06:24,433 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
CREATE DATABASE
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
# project_google_horeca_reviews                                                            (NAME DATABASE)
# │
# ├── horca_parameters_client                                                              (NAME SCHEMA)
# │   └── client_data
# │       ├── client_name (TXT)                                                                      (NAME TABLE)
# │       ├── client_id (SERIAL)                                                           (NAME ID)
# │       ├── client_data (JSONB)                                                          (NAME DATA)
# │       └── created_at (TIMESTAMP)                                                       (NAME TIME-CREATED)
# │
# ├── google_account_info
# │   └── account_data
# │       ├── account_id (SERIAL)
# │       ├── account_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# ├── standard_strings_review
# │   └── standard_string
# │       ├── string_id (SERIAL)
# │       ├── string_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# │
# │
# └── created_horeca_reviews
#     └── reviews_data
#         ├── client_name (TXT)
#         ├── review_id (SERIAL)
#         ├── review_data (JSONB)
#         └── created_at (TIMESTAMP)
#         └── review_count (INTEGER)

2024-02-21 23:06:24,433 - INFO - [92mDatabase [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-21 23:14:24,548 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-21 23:14:24,548 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-21 23:14:24,548 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-21 23:14:24,548 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-21 23:14:24,558 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-21 23:14:24,558 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-21 23:14:24,558 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-21 23:14:24,558 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 23:14:24,558 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-21 23:14:26,932 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-21 23:14:26,932 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-21 23:14:26,932 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-21 23:14:29,237 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-21 23:14:29,237 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-21 23:14:29,237 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-21 23:14:29,245 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-21 23:14:29,245 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-21 23:14:29,245 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-21 23:14:29,245 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-21 23:14:29,245 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-21 23:14:29,245 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-21 23:14:29,245 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-21 23:14:29,245 - INFO - [96mAttempting to create database:[0m
2024-02-21 23:14:29,245 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 23:14:29,245 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-21 23:14:29,245 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-21 23:14:29,245 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-21 23:14:29,246 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-21 23:14:29,246 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-21 23:14:29,246 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-21 23:14:29,284 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-21 23:14:29,284 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 23:14:29,284 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 23:14:29,297 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 23:14:29,297 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-21 23:14:29,297 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-21 23:14:29,297 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 23:14:29,297 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-21 23:14:29,297 - INFO - [94mAttempting to add following line:[0m
2024-02-21 23:14:29,298 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 23:14:29,298 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-21 23:14:29,298 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-21 23:14:29,298 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-21 23:14:29,298 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-21 23:14:29,298 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-21 23:14:35,669 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-21 23:14:35,669 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-21 23:14:35,669 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-21 23:14:35,681 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-21 23:14:35,681 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-21 23:14:35,682 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-21 23:14:35,682 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-21 23:14:39,407 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-21 23:14:39,407 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
# project_google_horeca_reviews                                                            (NAME DATABASE)
# │
# ├── horca_parameters_client                                                              (NAME SCHEMA)
# │   └── client_data
# │       ├── client_name (TXT)                                                                      (NAME TABLE)
# │       ├── client_id (SERIAL)                                                           (NAME ID)
# │       ├── client_data (JSONB)                                                          (NAME DATA)
# │       └── created_at (TIMESTAMP)                                                       (NAME TIME-CREATED)
# │
# ├── google_account_info
# │   └── account_data
# │       ├── account_id (SERIAL)
# │       ├── account_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# ├── standard_strings_review
# │   └── standard_string
# │       ├── string_id (SERIAL)
# │       ├── string_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# │
# │
# └── created_horeca_reviews
#     └── reviews_data
#         ├── client_name (TXT)
#         ├── review_id (SERIAL)
#         ├── review_data (JSONB)
#         └── created_at (TIMESTAMP)
#         └── review_count (INTEGER)

2024-02-21 23:14:39,407 - INFO - [92mDatabase [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-21 23:14:39,407 - INFO - [94mVerifying schema creation...[0m
2024-02-21 23:14:58,978 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
2024-02-21 23:15:06,826 - ERROR - [91mError: Schema google_account_info not found.[0m
2024-02-21 23:15:10,691 - ERROR - [91mError: Schema standard_strings_review not found.[0m
2024-02-21 23:15:13,221 - ERROR - [91mError: Schema created_horeca_reviews not found.[0m
2024-02-22 16:24:11,083 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 16:24:11,083 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 16:24:11,083 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 16:24:11,083 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 16:24:22,553 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 16:24:22,554 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 16:24:22,554 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 16:24:22,554 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 16:24:28,820 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 16:24:28,820 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 16:24:28,820 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 16:24:28,820 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 16:24:28,820 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 16:24:33,207 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 16:24:33,208 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 16:24:33,208 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 16:24:45,004 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 16:24:45,004 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 16:24:45,004 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 16:24:45,022 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 16:24:45,022 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 16:24:45,022 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 16:24:45,022 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 16:24:45,022 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 16:24:45,022 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 16:24:45,022 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 16:24:45,023 - INFO - [96mAttempting to create database:[0m
2024-02-22 16:24:45,023 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 16:24:45,024 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 16:24:45,024 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 16:24:45,024 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 16:24:45,029 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 16:24:45,030 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 16:24:45,030 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 16:24:45,075 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 16:24:45,075 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 16:24:45,075 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 16:24:45,091 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 16:24:45,091 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 16:24:45,091 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 16:24:45,091 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 16:24:45,091 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 16:24:45,092 - INFO - [94mAttempting to add following line:[0m
2024-02-22 16:24:45,092 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 16:24:45,092 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 16:24:45,092 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-22 16:24:45,092 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 16:24:45,092 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 16:24:45,092 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 16:24:51,480 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 16:24:51,480 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 16:24:51,480 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 16:24:51,494 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 16:24:51,494 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 16:24:51,494 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 16:24:51,494 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 16:25:20,259 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 16:25:20,259 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
# project_google_horeca_reviews                                                            (NAME DATABASE)
# │
# ├── horca_parameters_client                                                              (NAME SCHEMA)
# │   └── client_data
# │       ├── client_name (TXT)                                                                      (NAME TABLE)
# │       ├── client_id (SERIAL)                                                           (NAME ID)
# │       ├── client_data (JSONB)                                                          (NAME DATA)
# │       └── created_at (TIMESTAMP)                                                       (NAME TIME-CREATED)
# │
# ├── google_account_info
# │   └── account_data
# │       ├── account_id (SERIAL)
# │       ├── account_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# ├── standard_strings_review
# │   └── standard_string
# │       ├── string_id (SERIAL)
# │       ├── string_data (JSONB)
# │       └── created_at (TIMESTAMP)
# │
# │
# │
# └── created_horeca_reviews
#     └── reviews_data
#         ├── client_name (TXT)
#         ├── review_id (SERIAL)
#         ├── review_data (JSONB)
#         └── created_at (TIMESTAMP)
#         └── review_count (INTEGER)

2024-02-22 16:25:20,259 - INFO - [92mDatabase [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 16:25:20,259 - INFO - [94mVerifying schema creation...[0m
2024-02-22 16:25:24,848 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
2024-02-22 16:25:28,893 - ERROR - [91mError: Schema google_account_info not found.[0m
2024-02-22 16:25:31,119 - ERROR - [91mError: Schema standard_strings_review not found.[0m
2024-02-22 16:25:33,203 - ERROR - [91mError: Schema created_horeca_reviews not found.[0m
2024-02-22 21:18:04,827 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 21:18:04,827 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 21:18:04,827 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 21:18:04,827 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 21:18:04,837 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 21:18:04,837 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 21:18:04,838 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 21:18:04,838 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:18:04,838 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 21:18:07,455 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 21:18:07,455 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 21:18:07,455 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:18:11,253 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 21:18:11,253 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 21:18:11,254 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 21:18:11,261 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 21:18:11,261 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 21:18:11,261 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 21:18:11,261 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 21:18:11,261 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 21:18:11,261 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 21:18:11,261 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 21:18:11,261 - INFO - [96mAttempting to create database:[0m
2024-02-22 21:18:11,261 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:18:11,262 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 21:18:11,262 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 21:18:11,262 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:18:11,262 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 21:18:11,263 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:18:11,263 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 21:18:11,304 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 21:18:11,304 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:18:11,304 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:18:11,317 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:18:11,317 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 21:18:11,317 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 21:18:11,317 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:18:11,317 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 21:18:11,317 - INFO - [94mAttempting to add following line:[0m
2024-02-22 21:18:11,317 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:18:11,317 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 21:18:11,318 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-22 21:18:11,318 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 21:18:11,318 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:18:11,318 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 21:18:17,703 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 21:18:17,704 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:18:17,704 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:18:17,718 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:18:17,718 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 21:18:17,718 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 21:18:17,718 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:19:04,486 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 21:19:04,486 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE

2024-02-22 21:19:04,486 - INFO - [92mDatabase [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 21:19:04,486 - INFO - [94mVerifying schema creation...[0m
2024-02-22 21:19:11,388 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
2024-02-22 21:19:14,121 - ERROR - [91mError occurred while creating schema for database project_google_reviews: psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
[0m
2024-02-22 21:30:07,174 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 21:30:07,174 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 21:30:07,174 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 21:30:07,174 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 21:30:07,187 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 21:30:07,187 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 21:30:07,187 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 21:30:07,187 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:30:07,187 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 21:30:09,326 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 21:30:09,326 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 21:30:09,326 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:30:11,582 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 21:30:11,582 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 21:30:11,582 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 21:30:11,590 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 21:30:11,590 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 21:30:11,590 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 21:30:11,590 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 21:30:11,590 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 21:30:11,590 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 21:30:11,590 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 21:30:11,590 - INFO - [96mAttempting to create database:[0m
2024-02-22 21:30:11,590 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:30:11,591 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 21:30:11,591 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 21:30:11,591 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:30:11,592 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 21:30:11,592 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:30:11,592 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 21:30:11,633 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 21:30:11,633 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:30:11,633 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:30:11,646 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:30:11,646 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 21:30:11,646 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 21:30:11,646 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:30:11,646 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 21:30:11,646 - INFO - [94mAttempting to add following line:[0m
2024-02-22 21:30:11,646 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:30:11,646 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 21:30:11,646 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-22 21:30:11,646 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 21:30:11,646 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:30:11,646 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 21:30:18,041 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 21:30:18,041 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:30:18,041 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:30:18,054 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:30:18,054 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 21:30:18,054 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 21:30:18,054 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:30:21,490 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 21:30:21,491 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE

2024-02-22 21:30:21,491 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 21:30:21,491 - INFO - [94mVerifying schema creation...[0m
2024-02-22 21:30:40,426 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
2024-02-22 21:30:43,567 - ERROR - [91mError: Schema google_account_info not found.[0m
2024-02-22 21:30:45,677 - ERROR - [91mError: Schema standard_strings_review not found.[0m
2024-02-22 21:30:48,168 - ERROR - [91mError: Schema created_horeca_reviews not found.[0m
2024-02-22 21:35:56,176 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 21:35:56,176 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 21:35:56,177 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 21:35:56,177 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 21:35:56,187 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 21:35:56,187 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 21:35:56,187 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 21:35:56,187 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:35:56,187 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 21:35:58,481 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 21:35:58,482 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 21:35:58,482 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:36:01,375 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 21:36:01,375 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 21:36:01,375 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 21:36:01,383 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 21:36:01,383 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 21:36:01,383 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 21:36:01,383 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 21:36:01,383 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 21:36:01,383 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 21:36:01,383 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 21:36:01,383 - INFO - [96mAttempting to create database:[0m
2024-02-22 21:36:01,383 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:36:01,383 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 21:36:01,384 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 21:36:01,384 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:36:01,385 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 21:36:01,385 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:36:01,385 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 21:36:01,417 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 21:36:01,417 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:36:01,417 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:36:01,429 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:36:01,429 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 21:36:01,429 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 21:36:01,429 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:36:01,429 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 21:36:01,429 - INFO - [94mAttempting to add following line:[0m
2024-02-22 21:36:01,429 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:36:01,429 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 21:36:01,429 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-22 21:36:01,430 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 21:36:01,430 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:36:01,430 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 21:36:07,824 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 21:36:07,824 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:36:07,824 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:36:07,838 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:36:07,838 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 21:36:07,838 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 21:36:07,838 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:36:11,407 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 21:36:11,407 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-22 21:36:11,407 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 21:36:11,407 - INFO - [94mVerifying schema creation...[0m
2024-02-22 21:36:15,390 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
2024-02-22 21:36:19,039 - ERROR - [91mError: Schema google_account_info not found.[0m
2024-02-22 21:36:21,736 - ERROR - [91mError: Schema standard_strings_review not found.[0m
2024-02-22 21:36:24,325 - ERROR - [91mError: Schema created_horeca_reviews not found.[0m
2024-02-22 21:43:53,374 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 21:43:53,374 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 21:43:53,374 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 21:43:53,374 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 21:43:53,384 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 21:43:53,384 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 21:43:53,384 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 21:43:53,384 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:43:53,384 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 21:43:56,149 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 21:43:56,149 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 21:43:56,149 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:44:06,661 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 21:44:06,661 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 21:44:06,661 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 21:44:06,669 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 21:44:06,669 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 21:44:06,670 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 21:44:06,670 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 21:44:06,670 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 21:44:06,670 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 21:44:06,670 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 21:44:06,670 - INFO - [96mAttempting to create database:[0m
2024-02-22 21:44:06,670 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:44:06,670 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 21:44:06,670 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 21:44:06,670 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:44:06,671 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 21:44:06,671 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:44:06,671 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 21:44:06,733 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 21:44:06,733 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:44:06,733 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:44:06,746 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:44:06,746 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 21:44:06,746 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 21:44:06,746 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:44:06,746 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 21:44:06,746 - INFO - [94mAttempting to add following line:[0m
2024-02-22 21:44:06,746 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:44:06,746 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 21:44:06,746 - INFO - [95mlocal	  project_google_reviews	 project_google_reviews_usr     md5[0m
2024-02-22 21:44:06,747 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 21:44:06,747 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:44:06,747 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 21:44:13,148 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 21:44:13,148 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:44:13,148 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:44:13,161 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:44:13,161 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 21:44:13,161 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 21:44:13,161 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:44:23,973 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 21:44:23,973 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-22 21:44:23,973 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 21:44:23,973 - INFO - [94mVerifying schema creation...[0m
2024-02-22 21:46:30,499 - ERROR - [91mError occurred while creating schema for database project_google_reviews: psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  password authentication failed for user "postgres"
[0m
2024-02-22 21:46:33,380 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 21:46:33,380 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 21:46:33,380 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 21:46:33,380 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 21:46:33,390 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 21:46:33,390 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 21:46:33,390 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 21:46:33,390 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:46:33,390 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 21:46:35,491 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 21:46:35,492 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 21:46:35,492 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:46:37,311 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 21:46:37,311 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 21:46:37,311 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 21:46:37,319 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 21:46:37,319 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 21:46:37,319 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 21:46:37,319 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 21:46:37,319 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 21:46:37,319 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 21:46:37,319 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 21:46:37,319 - INFO - [96mAttempting to create database:[0m
2024-02-22 21:46:37,319 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:46:37,320 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 21:46:37,320 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 21:46:37,320 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:46:37,321 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 21:46:37,321 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:46:37,321 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 21:46:37,348 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 21:46:37,348 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:46:37,349 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:46:37,361 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:46:37,361 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 21:46:37,361 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 21:46:37,361 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:46:37,361 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 21:46:37,361 - INFO - [94mAttempting to add following line:[0m
2024-02-22 21:46:37,362 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:46:37,362 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 21:46:37,362 - INFO - [95mlocal	  project_google_reviews      project_google_reviews_usr     md5[0m
2024-02-22 21:46:37,362 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 21:46:37,362 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:46:37,362 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 21:46:43,729 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 21:46:43,729 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:46:43,729 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:46:43,742 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:46:43,742 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 21:46:43,742 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 21:46:43,742 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:46:52,409 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 21:46:52,409 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-22 21:46:52,410 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 21:46:52,410 - INFO - [94mVerifying schema creation...[0m
2024-02-22 21:46:55,725 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
2024-02-22 21:46:59,335 - ERROR - [91mError: Schema google_account_info not found.[0m
2024-02-22 21:47:01,051 - ERROR - [91mError: Schema standard_strings_review not found.[0m
2024-02-22 21:47:03,281 - ERROR - [91mError: Schema created_horeca_reviews not found.[0m
2024-02-22 21:48:34,280 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 21:48:34,280 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 21:48:34,280 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 21:48:34,280 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 21:48:34,289 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 21:48:34,290 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 21:48:34,290 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 21:48:34,290 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:48:34,290 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 21:48:36,336 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 21:48:36,336 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 21:48:36,336 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:48:37,921 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 21:48:37,922 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 21:48:37,922 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 21:48:37,929 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 21:48:37,929 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 21:48:37,929 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 21:48:37,929 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 21:48:37,930 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 21:48:37,930 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 21:48:37,930 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 21:48:37,930 - INFO - [96mAttempting to create database:[0m
2024-02-22 21:48:37,930 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:48:37,930 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 21:48:37,930 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 21:48:37,930 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:48:37,931 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 21:48:37,931 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:48:37,931 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 21:48:37,977 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 21:48:37,977 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:48:37,977 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:48:37,990 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:48:37,990 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 21:48:37,990 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 21:48:37,990 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:48:37,990 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 21:48:37,990 - INFO - [94mAttempting to add following line:[0m
2024-02-22 21:48:37,990 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:48:37,990 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 21:48:37,990 - INFO - [95mlocal	project_google_reviews	project_google_reviews_usr	md5[0m
2024-02-22 21:48:37,990 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 21:48:37,990 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:48:37,990 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 21:48:44,373 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 21:48:44,373 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:48:44,373 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:48:44,386 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:48:44,386 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 21:48:44,386 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 21:48:44,386 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:48:47,471 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 21:48:47,471 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-22 21:48:47,472 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 21:48:47,472 - INFO - [94mVerifying schema creation...[0m
2024-02-22 21:48:49,959 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
2024-02-22 21:48:52,429 - ERROR - [91mError: Schema google_account_info not found.[0m
2024-02-22 21:49:43,335 - INFO - HIIIIIIIIIIIIIIIIIIIIIII
2024-02-22 21:49:43,335 - INFO - [96mStarting[0m[93m main.py[0m [96m python3 script ...[0m
2024-02-22 21:49:43,335 - INFO - [96mCalling[0m[93m start_posgresql.py[0m [96mservice -function[0m
2024-02-22 21:49:43,335 - INFO - [96mExecuting start_postgresql.sh script[0m
2024-02-22 21:49:43,345 - INFO - [92mPostgreSQL service started successfully.[0m
2024-02-22 21:49:43,345 - INFO - [96mCalling[0m[93m create_new_postgresql_user.py[0m [96mservice -function[0m
2024-02-22 21:49:43,345 - INFO - [94mAttempting to create a new database user with corresponding password:[0m
2024-02-22 21:49:43,345 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:49:43,345 - INFO - [96mPassword:        [95mOo51knSSV3OSwfuy8WFu[0m
2024-02-22 21:49:45,314 - ERROR - [91mError occurred: Command 'sudo -u postgres psql -c "CREATE USER project_google_reviews_usr WITH PASSWORD 'Oo51knSSV3OSwfuy8WFu';"' returned non-zero exit status 1.[0m
2024-02-22 21:49:45,314 - INFO - [94mAttempting to confirm creation of a new database user:[0m
2024-02-22 21:49:45,314 - INFO - [96mUser:            [95mproject_google_reviews_usr[0m
2024-02-22 21:49:46,539 - ERROR - [91mError occurred: Command 'psql -U project_google_reviews_usr -W' returned non-zero exit status 2.[0m
2024-02-22 21:49:46,539 - INFO - [92mThe error should indicate: 'peer auth failed' because we haven't yet added an entry to the 'pg_hba.conf' file for the user database and the md5 authentication method.[0m
2024-02-22 21:49:46,539 - INFO - [96mCalling[0m[93m create_database_and_confirm_creation.py[0m [96mservice -function[0m
2024-02-22 21:49:46,547 - INFO - [96mAttempting to connect to the following database:[0m
2024-02-22 21:49:46,547 - INFO - [94mdatabase:[0m[95m        'postgres'       [0m
2024-02-22 21:49:46,548 - INFO - [94muser:[0m[95m            'postgres'         [0m
2024-02-22 21:49:46,548 - INFO - [94mpassword:[0m[95m        'postgres'         [0m
2024-02-22 21:49:46,548 - INFO - [94mhost:[0m[95m            'localhost'         [0m
2024-02-22 21:49:46,548 - INFO - [94mport:[0m[95m            '5432'        [0m
2024-02-22 21:49:46,548 - INFO - [92mSuccessfully connected to the database.[0m
2024-02-22 21:49:46,548 - INFO - [96mAttempting to create database:[0m
2024-02-22 21:49:46,548 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:49:46,548 - ERROR - [91mAn error occurred: database "project_google_reviews" already exists
[0m
2024-02-22 21:49:46,548 - INFO - [96mAttempting to confirm creation of database:[0m
2024-02-22 21:49:46,548 - INFO - [92mDatabase:[0m[95m      'project_google_reviews'[0m
2024-02-22 21:49:46,549 - INFO - [92mDatabase:[95m     'project_google_reviews'[0m [92m created successfully.[0m
2024-02-22 21:49:46,549 - INFO - [96mCalling[0m[93m stop_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:49:46,549 - INFO - [96mExecuting stop_postgresql.sh script[0m
2024-02-22 21:49:46,605 - INFO - [92mPostgreSQL service stopped successfully.[0m
2024-02-22 21:49:46,605 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:49:46,605 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:49:46,618 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:49:46,618 - INFO - [96mCalling[0m[93m edit_pg_hba_postgresql_config_file.py.py[0m [96mservice -function[0m
2024-02-22 21:49:46,618 - INFO - [94mAttempting to add new entry within 'pg_hba.conf' postgreSQL authentication file:[0m
2024-02-22 21:49:46,618 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:49:46,618 - INFO - [96mUser:                [95mproject_google_reviews_usr[0m
2024-02-22 21:49:46,618 - INFO - [94mAttempting to add following line:[0m
2024-02-22 21:49:46,618 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:49:46,618 - INFO - [95m# TYPE  DATABASE  USER     ADDRESS     METHOD[0m
2024-02-22 21:49:46,618 - INFO - [95mlocal	project_google_reviews		project_google_reviews_usr	md5[0m
2024-02-22 21:49:46,619 - INFO - [92mLine added successfully to pg_hba.conf.[0m
2024-02-22 21:49:46,619 - INFO - [96mCalling[0m[93m restart_postgresql.py[0m [96mservice -function[0m
2024-02-22 21:49:46,619 - INFO - [96mExecuting restart_postgresql.sh script[0m
2024-02-22 21:49:53,017 - INFO - [92mPostgreSQL service restarted successfully.[0m
2024-02-22 21:49:53,017 - INFO - [96mCalling[0m[93m check_status_postgresql_service.py[0m [96mservice -function[0m
2024-02-22 21:49:53,017 - INFO - [96mExecuting check_status_postgresql_service.sh script[0m
2024-02-22 21:49:53,030 - INFO - [92mStatus check on postgreSQL service completed successfully.[0m
2024-02-22 21:49:53,030 - INFO - [96mCalling[0m[93m create_schema_new_database.py[0m [96mservice -function[0m
2024-02-22 21:49:53,030 - INFO - [94mAttempting to create specified schema for database:[0m
2024-02-22 21:49:53,030 - INFO - [96mDatabase:            [95mproject_google_reviews[0m
2024-02-22 21:49:59,404 - INFO - [94mOutput of creating schema for database [0m [95mproject_google_reviews:[0m
2024-02-22 21:49:59,404 - INFO - -- Create the project_google_horeca_reviews database
CREATE DATABASE project_google_horeca_reviews;
-- Connect to the project_google_horeca_reviews database
\c project_google_horeca_reviews;
You are now connected to database "project_google_horeca_reviews" as user "postgres".
-- Create the horca_parameters_client schema
CREATE SCHEMA IF NOT EXISTS horca_parameters_client;
CREATE SCHEMA
-- Create the horca_parameters_client.client_data table
CREATE TABLE IF NOT EXISTS horca_parameters_client.client_data (
    client_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the google_account_info schema
CREATE SCHEMA IF NOT EXISTS google_account_info;
CREATE SCHEMA
-- Create the google_account_info.account_data table
CREATE TABLE IF NOT EXISTS google_account_info.account_data (
    account_id SERIAL PRIMARY KEY,
    account_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the standard_strings_review schema
CREATE SCHEMA IF NOT EXISTS standard_strings_review;
CREATE SCHEMA
-- Create the standard_strings_review.standard_string table
CREATE TABLE IF NOT EXISTS standard_strings_review.standard_string (
    string_id SERIAL PRIMARY KEY,
    string_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE
-- Create the created_horeca_reviews schema
CREATE SCHEMA IF NOT EXISTS created_horeca_reviews;
CREATE SCHEMA
-- Create the created_horeca_reviews.reviews_data table
CREATE TABLE IF NOT EXISTS created_horeca_reviews.reviews_data (
    review_id SERIAL PRIMARY KEY,
    client_name TEXT NOT NULL,
    review_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    review_count INTEGER
);
CREATE TABLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA horca_parameters_client TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA google_account_info TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA standard_strings_review TO project_google_reviews_usr;
GRANT
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA created_horeca_reviews TO project_google_reviews_usr;
GRANT

2024-02-22 21:49:59,404 - INFO - [92mSchema for database: [0m[95mproject_google_reviews[0m[92m created successfully.[0m
2024-02-22 21:49:59,404 - INFO - [94mVerifying schema creation...[0m
2024-02-22 21:50:02,143 - ERROR - [91mError: Schema horca_parameters_client not found.[0m
